title: "bourbonify-jekyll"
author: "Andrzej Kłapeć"
email: your-email@domain.com
keywords: "comma, separated, keywords"
description: "Simple boilerplate for quickly setting up Jekyll with Normalize, Bourbon and Neat."

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://github.com/klapec" # the base hostname & protocol for your site

markdown: redcarpet
redcarpet:
  extensions: ["smart", "autolink", "tables", "no_intra_emphasis", "strikethrough", "underline", "quote", "footnotes"]

exclude: ['assets/src', 'node_modules', 'package.json', 'gulpfile.js', 'LICENSE', 'README.md', 'bourbonify-jekyll.sublime-project', 'bower_components', 'bower.json']

timezone: Europe/Warsaw

permalink: none
